version: "3" # composeファイルのバージョン
services: 
    omusubi-clone: # サービス名
        build: . # ビルドに使うDockerfileの場所
        environment:
            - DRIVER
            - DSN
        ports:
            - 8080:8080
        tty: true # コンテナの永続化
        volumes:
            - ./:/omusubi-clone # マウントディレクトリ
        depends_on: 
            - omusubi-mysql # 依存関係 omusubi-clone->mysqlの順で起動

    omusubi-mysql:
        build: ./mysql/
        volumes:
            # 初期データを投入するSQLが格納されているdir
            - ./mysql/sql:/docker-entrypoint-initdb.d
            # 永続化するときにマウントするdir
            - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - TZ
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        
        
